[package]
name = "tractor-beam-flutter-bridge"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

[lints.clippy]
all = "warn"
pedantic = "warn"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.13.0"
tractor-beam-application = { path = "../bridge-application" }
tractor-beam-core = { path = "../bridge-core" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
atomic-write-file = "0.3.0"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_Security_Cryptography",
    "Win32_System_Memory",
] }

[dev-dependencies]
tempfile = "3.23.0"
